name: Build and deploy ASP app to Azure Web App - Githubappp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore

      - name: Publish to folder
        run: msbuild /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="\published\"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: ASP-app
          path: '/published/**'

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: ASP-app
          
            - uses: Azure/login@v1
    with:
      creds: '{"clientId":"${{ secrets.a187812f-7bf4-4414-abab-3691e1c8c287 }}","clientSecret":"${{ secrets.qT08Q~uopZ-FTP.CpJJFl397SCJMx7fMMrCKlb0q }}","subscriptionId":"${{ secrets.a21dd5ae-f19b-44f9-85b8-a07ca7b8a57c }}","tenantId":"${{ secrets.ae9ffe14-d4a5-41ea-b86d-d371eb10dad4 }}"}'


      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Githubappp'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_d3208ae7ba774b8fa0d5a616e2481bb9 }}
          package: .
      
